# Generated by Django 4.1 on 2022-10-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mypost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('intro', models.TextField()),
                ('body', models.TextField()),
                ('my_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-my_date'],
            },
        ),
    ]
