# Generated by Django 4.1 on 2022-10-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
