# Generated by Django 4.1 on 2022-10-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_custom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
